version: "3.2"
services:
  pg:
    restart: always
    image: postgres:12.1
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - "../volumes/postgres:/var/lib/postgresql/data"
    env_file:
      - .env.development

  # https://kb.objectrocket.com/redis/run-redis-with-docker-compose-1055
  redis:
    restart: always
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - "../volumes/redis:/data"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"

  es5:
    image: elasticsearch_56
    container_name: elasticsearch_56
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "../volumes/elasticsearch5:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200

  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch_7.15
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "../volumes/elasticsearch7:/usr/share/elasticsearch/data"
    ports:
      - 9500:9200

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 8081:8081
      - 27017:27017
    volumes:
      - ../volumes/mongodb:/data/db
